### ISSUE TITLE
License

### ISSUE THREAD

**Issue by kvlahromei** [open311/swagger-open311#3]
Corresponding to swagger, we need to pick a license for the API: https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#licenseObject

I didn't found a hint on how we license Open311 and I'm not sure if this refers to the YAML definitions or also to the generated class stubs or even the data gathered with the API? :confused:

**Comment by petterreinholdtsen** [comment]
I would suggest something placing in the public domain, perhaps
<URL: http://www.opendatacommons.org/licenses/pddl/ >,
<URL: http://creativecommons.org/publicdomain/mark/1.0/deed.no > or
<URL: http://creativecommons.org/about/cc0 > would be a good fit.

**Comment by petterreinholdtsen** [comment]
I would suggest something placing in the public domain, perhaps
http://www.opendatacommons.org/licenses/pddl/ ,
http://creativecommons.org/publicdomain/mark/1.0/deed.no and
http://creativecommons.org/about/cc0 .

**Comment by kvlahromei** [comment]
I would be also ok with a PD license.

Nevertheless we should point out what the community wants:
- attribution and authorship
- way of openness
- copyleft
- protection for trademark and the open311 logo / badge

This needs to be discussed for different aspects
- "informal" API specs
- Swagger YAML definitions
- Swagger generated class stubs
- Open311 content

My personal opinion towards this things:
- we make attribution on a community approach and have no formal way to verify any standard compilance
  *\* it's ok if people just claim that they offer compatible clients/servers
- we don't need to have a copyleft on the source (YAML and classes) and force people to open their sources, too
- we don't want to tell organisations how they have to license their content
  ergo sum it's public domain for me :-)

**Comment by kvlahromei** [comment]
As nobody complaint about PD, I just added it and refer to the server TOS for license of the materials

**Comment by petterreinholdtsen** [comment]
While I very much welcome the decision to go for public domain, I believe the implementation is
broken. Pointing to https://en.wikipedia.org/wiki/Public_domain as the license is not going to work
for a large part of the world.  For most of the the part outside USA, public domain is not an option
in the legal framework protecting copyright proected works.  This is the reason the CC and
OpenDataCommons licenses are forumulated the way they are, to get the closest thing to public
domain in these countries.  For example, here in Norway, it is not possible to "resign" authorship
as in USA.

Please pick one of the proposed lisenses instead of pointing to wikipedia, as these also work outside USA.

**Comment by kvlahromei** [comment]
it's my mistake, as I first pushed it under PD, while @philipashlock refered an old discussion over at the mailinglist. There the prefer also CC BY 3.0, so I updated the file already.

Sorry for the confusion :-/
